### ISSUE TITLE
[Addition] Magma Infused Elytra

### ISSUE THREAD

**Issue by rasfdh** [velolib/veloSMP-Resource-Pack#10]
### What I'm Requesting
IDK FUCK https://www.planetminecraft.com/texture-pack/magma-infused-elytra/

### The Texture/Model
IDK https://www.planetminecraft.com/texture-pack/magma-infused-elytra/

### Why I want to add it
LOOKS SO FUCKING COOL

IF ANY IS WRONG SPAM PING ME PLS

**Comment by velolib** [comment]
Hi revan, this will be added. Big thanks for choosing this texture, because it's already implemented in an older version! Thanks!

**Comment by velolib** [comment]
Actually, I forgot 1 thing. What's gonna be the name for it?

**Comment by rasfdh** [comment]
"Molten Forged Elytra" idont fuckign know but go forr irt PLSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS

**Comment by rasfdh** [comment]
fagog pls answer i beg yuoy

**Comment by velolib** [comment]
OKAY
