### ISSUE TITLE
[Additions] My Elytra Suggestion

### ISSUE THREAD

**Issue by Exomi039** [velolib/veloSMP-Resource-Pack#11]
### What I'm Requesting
ELYTRA GOBLOK

### The Texture/Model
![skylartechicon](https://user-images.githubusercontent.com/67255325/87241725-237c5500-c450-11ea-9a86-d5c468e54ac9.png)

### Why I want to add it
[LO SURUH IDOT

**Comment by velolib** [comment]
What's the name of the elytra?

**Comment by velolib** [comment]
Also, where is the MODEL?

**Comment by Exomi039** [comment]
![skylartech](https://user-images.githubusercontent.com/67255325/87242631-b7521f00-c458-11ea-9f77-1d42d96d83de.png)

**Comment by Exomi039** [comment]
Aeon Soul

**Comment by velolib** [comment]
Thanks!
