### ISSUE TITLE
[Addition] Solar Wings Elytra Texture

### ISSUE THREAD

**Issue by mirzaholic** [velolib/veloSMP-Resource-Pack#13]
### What I'm Requesting
Elytra texture

### The Texture/Model
https://www.planetminecraft.com/texture-pack/solar-wings-from-terraria/

### Why I want to add it
i like Terraria solar wings and because the texture was in VeloSMP Season 1 and it looked cool

**Comment by mirzaholic** [comment]
ez

**Comment by mirzaholic** [comment]
name  is "HellWing"

**Comment by velolib** [comment]
Thanks for the suggestion. Also another thanks for following to format! Added.
