### ISSUE TITLE
[Addition] Rainbow Animated Sword (diamond sword replacement)

### ISSUE THREAD

**Issue by outrowed** [velolib/veloSMP-Resource-Pack#6]
### What I'm Requesting
Texture

### The Texture/Model
![rainbow](https://user-images.githubusercontent.com/59441185/85709421-6ed3fb00-b70f-11ea-93c0-5a1b77c02c37.png)

### Why I want to add it
Is the rainbow sword, the sword that looks cool.

**Comment by velolib** [comment]
Yeah, what's the name for it?

**Comment by outrowed** [comment]
oh, just "Soul Sword"

**Comment by outrowed** [comment]
its a reference from undertale

**Comment by velolib** [comment]
Cool ok done thank you
