### ISSUE TITLE
[Addition] shotgun (multishot crossbow replacement)

### ISSUE THREAD

**Issue by mirzaholic** [velolib/veloSMP-Resource-Pack#8]
### What I'm Requesting
texture

### The Texture/Model
https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.pikpng.com%2Fpngvi%2Fmimimx_fortnite-pump-shotgun-8-bit-gun-clipart%2F&psig=AOvVaw1rivrXArCrmZ14mvHpsBgW&ust=1593253424675000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCJjpqNahn-oCFQAAAAAdAAAAABAK

### Why I want to add it
its a shotgun and multishot crossbows are like crossbows

**Comment by velolib** [comment]
Can't. Texture is too large. Style wouldn't fit in.
